const elementCategory = ['alkali', 'alkaline earth', 'transition', 'post-transition', 'metalloid', 'nonmetal', 'halogen', 'noble gas', 'lanthanoid', 'actinoid'];

const elementsData = [
  {
    "name": "Hydrogen",
    "symbol": "H",
    "atomicNumber": 1,
    "block": "s-block",
    "group": 1,
    "period": 1,
    "category": "nonmetal",
    "electronConfig": "1s1",
    "yearDiscovered": 1766,
    "oxidationStates": "-1, +1",
    "electronegativity": 2.2,
    "ionisationEnergy": 1312,
    "atomicRadius": 0.53,
    "covalentRadius": 0.37,
    "vanDerWaalsRadius": 1.2,
    "phase": "gas",
    "heatOfFusion": 0.117,
    "heatOfVaporisation": 0.904,
    "molarHeatCapacity": 28.836,
    "meltingPoint": 13.99,
    "boilingPoint": 20.271,
    "density": "n/a",
    "atomicMass": 1.008,
    "crystalStructure": "hexagonal",
    "magneticOrdering": "diamagnetic",
    "casNumber": "1333-74-0",
    "bondingType": "diatomic",
    "": ""
  },
  {
    "name": "Helium",
    "symbol": "He",
    "atomicNumber": 2,
    "block": "s-block",
    "group": 18,
    "period": 1,
    "category": "noble gas",
    "electronConfig": "1s2",
    "yearDiscovered": 1868,
    "oxidationStates": 0,
    "electronegativity": "n/a",
    "ionisationEnergy": 2372,
    "atomicRadius": 0.31,
    "covalentRadius": 0.32,
    "vanDerWaalsRadius": 1.4,
    "phase": "gas",
    "heatOfFusion": 0.0138,
    "heatOfVaporisation": 0.0829,
    "molarHeatCapacity": 20.78,
    "meltingPoint": 0.95,
    "boilingPoint": 4.222,
    "density": "n/a",
    "atomicMass": 4.002602,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-59-7",
    "bondingType": "atomic",
    "": ""
  },
  {
    "name": "Lithium",
    "symbol": "Li",
    "atomicNumber": 3,
    "block": "s-block",
    "group": 1,
    "period": 2,
    "category": "alkali",
    "electronConfig": "[He] 2s1",
    "yearDiscovered": 1817,
    "oxidationStates": 1,
    "electronegativity": 0.98,
    "ionisationEnergy": 520,
    "atomicRadius": 1.67,
    "covalentRadius": 1.34,
    "vanDerWaalsRadius": 1.82,
    "phase": "solid",
    "heatOfFusion": 3,
    "heatOfVaporisation": 136,
    "molarHeatCapacity": 24.86,
    "meltingPoint": 453.65,
    "boilingPoint": 1603,
    "density": 0.534,
    "atomicMass": 6.94,
    "crystalStructure": "body-centered cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7439-93-2",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Beryllium",
    "symbol": "Be",
    "atomicNumber": 4,
    "block": "s-block",
    "group": 2,
    "period": 2,
    "category": "alkaline earth",
    "electronConfig": "[He] 2s2",
    "yearDiscovered": 1798,
    "oxidationStates": "+2, +1",
    "electronegativity": 1.57,
    "ionisationEnergy": 900,
    "atomicRadius": 1.12,
    "covalentRadius": 0.9,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 12.2,
    "heatOfVaporisation": 292,
    "molarHeatCapacity": 16.443,
    "meltingPoint": 1560,
    "boilingPoint": 2742,
    "density": 1.85,
    "atomicMass": 9.0121831,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-41-7",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Boron",
    "symbol": "B",
    "atomicNumber": 5,
    "block": "p-block",
    "group": 13,
    "period": 2,
    "category": "metalloid",
    "electronConfig": "[He] 2s2 2p1",
    "yearDiscovered": 1807,
    "oxidationStates": "3, 2, 1, -1, -5",
    "electronegativity": 2.04,
    "ionisationEnergy": 801,
    "atomicRadius": 0.87,
    "covalentRadius": 0.82,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 50.2,
    "heatOfVaporisation": 508,
    "molarHeatCapacity": 11.087,
    "meltingPoint": 2349,
    "boilingPoint": 4200,
    "density": 2.34,
    "atomicMass": 10.81,
    "crystalStructure": "rhombohedral",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-42-8",
    "bondingType": "covalent",
    "": ""
  },
  {
    "name": "Carbon",
    "symbol": "C",
    "atomicNumber": 6,
    "block": "p-block",
    "group": 14,
    "period": 2,
    "category": "nonmetal",
    "electronConfig": "[He] 2s2 2p2",
    "yearDiscovered": "Ancient",
    "oxidationStates": "+4, +3, +2, +1, 0, -1, -2, -3, -4",
    "electronegativity": 2.55,
    "ionisationEnergy": 1087,
    "atomicRadius": 0.67,
    "covalentRadius": 0.77,
    "vanDerWaalsRadius": 1.7,
    "phase": "solid",
    "heatOfFusion": 117,
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": 6.155,
    "meltingPoint": 3773.15,
    "boilingPoint": 5100.15,
    "density": 2.267,
    "atomicMass": 12.011,
    "crystalStructure": "face-centered diamond-cubic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-44-0",
    "bondingType": "covalent",
    "": ""
  },
  {
    "name": "Nitrogen",
    "symbol": "N",
    "atomicNumber": 7,
    "block": "p-block",
    "group": 15,
    "period": 2,
    "category": "nonmetal",
    "electronConfig": "[He] 2s2 2p3",
    "yearDiscovered": 1772,
    "oxidationStates": "5, 4, 3, 2, 1, -1, -2, -3",
    "electronegativity": 3.04,
    "ionisationEnergy": 1402,
    "atomicRadius": 0.56,
    "covalentRadius": 0.75,
    "vanDerWaalsRadius": 1.55,
    "phase": "gas",
    "heatOfFusion": 0.72,
    "heatOfVaporisation": 5.57,
    "molarHeatCapacity": 29.124,
    "meltingPoint": 63.15,
    "boilingPoint": 77.355,
    "density": 3.513,
    "atomicMass": 14.007,
    "crystalStructure": "hexagonal",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7727-37-9",
    "bondingType": "diatomic",
    "": ""
  },
  {
    "name": "Oxygen",
    "symbol": "O",
    "atomicNumber": 8,
    "block": "p-block",
    "group": 16,
    "period": 2,
    "category": "nonmetal",
    "electronConfig": "[He] 2s2 2p4",
    "yearDiscovered": 1774,
    "oxidationStates": "2, 1, -1, -2",
    "electronegativity": 3.44,
    "ionisationEnergy": 1314,
    "atomicRadius": 0.48,
    "covalentRadius": 0.73,
    "vanDerWaalsRadius": 1.52,
    "phase": "gas",
    "heatOfFusion": 0.444,
    "heatOfVaporisation": 6.82,
    "molarHeatCapacity": 29.378,
    "meltingPoint": 54.36,
    "boilingPoint": 90.188,
    "density": "n/a",
    "atomicMass": 15.999,
    "crystalStructure": "cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7782-44-7",
    "bondingType": "diatomic",
    "": ""
  },
  {
    "name": "Fluorine",
    "symbol": "F",
    "atomicNumber": 9,
    "block": "p-block",
    "group": 17,
    "period": 2,
    "category": "halogen",
    "electronConfig": "[He] 2s2 2p5",
    "yearDiscovered": 1670,
    "oxidationStates": -1,
    "electronegativity": 3.98,
    "ionisationEnergy": 1681,
    "atomicRadius": 0.42,
    "covalentRadius": 0.71,
    "vanDerWaalsRadius": 1.47,
    "phase": "gas",
    "heatOfFusion": 0.51,
    "heatOfVaporisation": 6.51,
    "molarHeatCapacity": 23,
    "meltingPoint": 53.48,
    "boilingPoint": 85.03,
    "density": "n/a",
    "atomicMass": 18.99840316,
    "crystalStructure": "cubic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7782-41-4",
    "bondingType": "atomic",
    "": ""
  },
  {
    "name": "Neon",
    "symbol": "Ne",
    "atomicNumber": 10,
    "block": "p-block",
    "group": 18,
    "period": 2,
    "category": "noble gas",
    "electronConfig": "[He] 2s2 2p6",
    "yearDiscovered": 1898,
    "oxidationStates": 0,
    "electronegativity": "n/a",
    "ionisationEnergy": 2081,
    "atomicRadius": 0.38,
    "covalentRadius": 0.69,
    "vanDerWaalsRadius": 1.54,
    "phase": "gas",
    "heatOfFusion": 0.335,
    "heatOfVaporisation": 1.71,
    "molarHeatCapacity": 20.79,
    "meltingPoint": 24.56,
    "boilingPoint": 27.104,
    "density": "n/a",
    "atomicMass": 20.1797,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-01-09",
    "bondingType": "atomic",
    "": ""
  },
  {
    "name": "Sodium",
    "symbol": "Na",
    "atomicNumber": 11,
    "block": "s-block",
    "group": 1,
    "period": 3,
    "category": "alkali",
    "electronConfig": "[Ne] 3s1",
    "yearDiscovered": 1807,
    "oxidationStates": "+1, -1",
    "electronegativity": 0.93,
    "ionisationEnergy": 496,
    "atomicRadius": 1.9,
    "covalentRadius": 1.54,
    "vanDerWaalsRadius": 2.27,
    "phase": "solid",
    "heatOfFusion": 2.6,
    "heatOfVaporisation": 97.42,
    "molarHeatCapacity": 28.23,
    "meltingPoint": 370.944,
    "boilingPoint": 1156.09,
    "density": 0.968,
    "atomicMass": 22.98976928,
    "crystalStructure": "body-centered cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-23-5",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Magnesium",
    "symbol": "Mg",
    "atomicNumber": 12,
    "block": "s-block",
    "group": 2,
    "period": 3,
    "category": "alkaline earth",
    "electronConfig": "[Ne] 3s2",
    "yearDiscovered": 1808,
    "oxidationStates": "+2, +1",
    "electronegativity": 1.31,
    "ionisationEnergy": 738,
    "atomicRadius": 1.45,
    "covalentRadius": 1.3,
    "vanDerWaalsRadius": 1.73,
    "phase": "solid",
    "heatOfFusion": 8.48,
    "heatOfVaporisation": 128,
    "molarHeatCapacity": 24.869,
    "meltingPoint": 923,
    "boilingPoint": 1363,
    "density": 1.738,
    "atomicMass": 24.305,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7439-95-4",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Aluminum",
    "symbol": "Al",
    "atomicNumber": 13,
    "block": "p-block",
    "group": 13,
    "period": 3,
    "category": "post-transition",
    "electronConfig": "[Ne] 3s2 3p1",
    "yearDiscovered": "Ancient",
    "oxidationStates": "+3, +2, +1, -1, -2",
    "electronegativity": 1.61,
    "ionisationEnergy": 578,
    "atomicRadius": 1.18,
    "covalentRadius": 1.18,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 10.71,
    "heatOfVaporisation": 284,
    "molarHeatCapacity": 24.2,
    "meltingPoint": 933.47,
    "boilingPoint": 2743,
    "density": 2.7,
    "atomicMass": 26.9815385,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7429-90-5",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Silicon",
    "symbol": "Si",
    "atomicNumber": 14,
    "block": "p-block",
    "group": 14,
    "period": 3,
    "category": "metalloid",
    "electronConfig": "[Ne] 3s2 3p2",
    "yearDiscovered": 1854,
    "oxidationStates": "4, 3, 2, 1 -1, -2, -3, -4",
    "electronegativity": 1.9,
    "ionisationEnergy": 787,
    "atomicRadius": 1.11,
    "covalentRadius": 1.11,
    "vanDerWaalsRadius": 2.1,
    "phase": "solid",
    "heatOfFusion": 50.21,
    "heatOfVaporisation": 359,
    "molarHeatCapacity": 19.789,
    "meltingPoint": 1687,
    "boilingPoint": 3538,
    "density": 2.329,
    "atomicMass": 28.085,
    "crystalStructure": "face-centered diamond-cubic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-21-3",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Phosphorus",
    "symbol": "P",
    "atomicNumber": 15,
    "block": "p-block",
    "group": 15,
    "period": 3,
    "category": "nonmetal",
    "electronConfig": "[Ne] 3s2 3p3",
    "yearDiscovered": 1669,
    "oxidationStates": "5, 4, 3, 2, 1, -1, -2, -3",
    "electronegativity": 2.19,
    "ionisationEnergy": 1012,
    "atomicRadius": 0.98,
    "covalentRadius": 1.06,
    "vanDerWaalsRadius": 1.8,
    "phase": "solid",
    "heatOfFusion": 0.66,
    "heatOfVaporisation": 12.4,
    "molarHeatCapacity": 23.824,
    "meltingPoint": 317.25,
    "boilingPoint": 553.15,
    "density": 1.823,
    "atomicMass": 30.973762,
    "crystalStructure": "body-centred cubic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7723-14-0",
    "bondingType": "covalent",
    "": ""
  },
  {
    "name": "Sulfur",
    "symbol": "S",
    "atomicNumber": 16,
    "block": "p-block",
    "group": 16,
    "period": 3,
    "category": "nonmetal",
    "electronConfig": "[Ne] 3s2 3p4",
    "yearDiscovered": "Ancient",
    "oxidationStates": "6, 5, 4, 3, 2, 1, -1, -2",
    "electronegativity": 2.58,
    "ionisationEnergy": 1000,
    "atomicRadius": 0.88,
    "covalentRadius": 1.02,
    "vanDerWaalsRadius": 1.8,
    "phase": "solid",
    "heatOfFusion": 1.727,
    "heatOfVaporisation": 45,
    "molarHeatCapacity": 22.75,
    "meltingPoint": 388.36,
    "boilingPoint": 717.8,
    "density": 2.07,
    "atomicMass": 32.06,
    "crystalStructure": "orthorhombic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7704-34-9",
    "bondingType": "covalent",
    "": ""
  },
  {
    "name": "Chlorine",
    "symbol": "Cl",
    "atomicNumber": 17,
    "block": "p-block",
    "group": 17,
    "period": 3,
    "category": "halogen",
    "electronConfig": "[Ne] 3s2 3p5",
    "yearDiscovered": 1774,
    "oxidationStates": "7, 6, 5, 4, 3, 2, 1, -1",
    "electronegativity": 3.16,
    "ionisationEnergy": 1251,
    "atomicRadius": 0.79,
    "covalentRadius": 0.99,
    "vanDerWaalsRadius": 1.75,
    "phase": "gas",
    "heatOfFusion": 6.406,
    "heatOfVaporisation": 20.41,
    "molarHeatCapacity": 33.949,
    "meltingPoint": 171.6,
    "boilingPoint": 239.11,
    "density": "n/a",
    "atomicMass": 35.45,
    "crystalStructure": "orthorhombic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7782-50-5",
    "bondingType": "covalent",
    "": ""
  },
  {
    "name": "Argon",
    "symbol": "Ar",
    "atomicNumber": 18,
    "block": "p-block",
    "group": 18,
    "period": 3,
    "category": "noble gas",
    "electronConfig": "[Ne] 3s2 3p6",
    "yearDiscovered": 1894,
    "oxidationStates": 0,
    "electronegativity": "n/a",
    "ionisationEnergy": 1521,
    "atomicRadius": 0.71,
    "covalentRadius": 0.97,
    "vanDerWaalsRadius": 1.88,
    "phase": "gas",
    "heatOfFusion": 1.18,
    "heatOfVaporisation": 6.53,
    "molarHeatCapacity": 20.85,
    "meltingPoint": 83.81,
    "boilingPoint": 87.302,
    "density": "n/a",
    "atomicMass": 39.948,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-37-1",
    "bondingType": "atomic",
    "": ""
  },
  {
    "name": "Potassium",
    "symbol": "K",
    "atomicNumber": 19,
    "block": "s-block",
    "group": 1,
    "period": 4,
    "category": "alkali",
    "electronConfig": "[Ar] 4s1",
    "yearDiscovered": 1807,
    "oxidationStates": "+1, -1",
    "electronegativity": 0.82,
    "ionisationEnergy": 419,
    "atomicRadius": 2.43,
    "covalentRadius": 1.96,
    "vanDerWaalsRadius": 2.75,
    "phase": "solid",
    "heatOfFusion": 2.33,
    "heatOfVaporisation": 76.9,
    "molarHeatCapacity": 29.6,
    "meltingPoint": 336.7,
    "boilingPoint": 1032,
    "density": 0.862,
    "atomicMass": 39.0983,
    "crystalStructure": "body-centered cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-09-07",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Calcium",
    "symbol": "Ca",
    "atomicNumber": 20,
    "block": "s-block",
    "group": 2,
    "period": 4,
    "category": "alkaline earth",
    "electronConfig": "[Ar] 4s2",
    "yearDiscovered": "Ancient",
    "oxidationStates": "+2, +1",
    "electronegativity": 1,
    "ionisationEnergy": 590,
    "atomicRadius": 1.94,
    "covalentRadius": 1.74,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 8.54,
    "heatOfVaporisation": 154.7,
    "molarHeatCapacity": 25.929,
    "meltingPoint": 1115,
    "boilingPoint": 1757,
    "density": 1.55,
    "atomicMass": 40.078,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-70-2",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Scandium",
    "symbol": "Sc",
    "atomicNumber": 21,
    "block": "d-block",
    "group": 3,
    "period": 4,
    "category": "transition",
    "electronConfig": "[Ar] 3d1 4s2",
    "yearDiscovered": 1876,
    "oxidationStates": "3, 2, 1",
    "electronegativity": 1.36,
    "ionisationEnergy": 633,
    "atomicRadius": 1.84,
    "covalentRadius": 1.44,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 14.1,
    "heatOfVaporisation": 332.7,
    "molarHeatCapacity": 25.52,
    "meltingPoint": 1814,
    "boilingPoint": 3109,
    "density": 2.985,
    "atomicMass": 44.955908,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-20-2",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Titanium",
    "symbol": "Ti",
    "atomicNumber": 22,
    "block": "d-block",
    "group": 4,
    "period": 4,
    "category": "transition",
    "electronConfig": "[Ar] 3d2 4s2",
    "yearDiscovered": 1791,
    "oxidationStates": "4, 3, 2, 1, -1, -2",
    "electronegativity": 1.54,
    "ionisationEnergy": 659,
    "atomicRadius": 1.76,
    "covalentRadius": 1.36,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 14.15,
    "heatOfVaporisation": 425,
    "molarHeatCapacity": 25.06,
    "meltingPoint": 1941,
    "boilingPoint": 3560,
    "density": 4.506,
    "atomicMass": 47.867,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-32-6",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Vanadium",
    "symbol": "V",
    "atomicNumber": 23,
    "block": "d-block",
    "group": 5,
    "period": 4,
    "category": "transition",
    "electronConfig": "[Ar] 3d3 4s2",
    "yearDiscovered": 1803,
    "oxidationStates": "5, 4, 3, 2, 1, -1, -3",
    "electronegativity": 1.63,
    "ionisationEnergy": 651,
    "atomicRadius": 1.71,
    "covalentRadius": 1.25,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 21.5,
    "heatOfVaporisation": 444,
    "molarHeatCapacity": 24.89,
    "meltingPoint": 2183,
    "boilingPoint": 3680,
    "density": 6,
    "atomicMass": 50.9415,
    "crystalStructure": "body-centered cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-62-2",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Chromium",
    "symbol": "Cr",
    "atomicNumber": 24,
    "block": "d-block",
    "group": 6,
    "period": 4,
    "category": "transition",
    "electronConfig": "[Ar] 3d5 4s1",
    "yearDiscovered": "Ancient",
    "oxidationStates": "6, 5, 4, 3, 2, 1, -1, -2, -4",
    "electronegativity": 1.66,
    "ionisationEnergy": 653,
    "atomicRadius": 1.66,
    "covalentRadius": 1.27,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 21,
    "heatOfVaporisation": 347,
    "molarHeatCapacity": 23.35,
    "meltingPoint": 2180,
    "boilingPoint": 2944,
    "density": 7.19,
    "atomicMass": 51.9961,
    "crystalStructure": "body-centered cubic",
    "magneticOrdering": "antiferromagnetic",
    "casNumber": "7440-47-3",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Manganese",
    "symbol": "Mn",
    "atomicNumber": 25,
    "block": "d-block",
    "group": 7,
    "period": 4,
    "category": "transition",
    "electronConfig": "[Ar] 3d5 4s2",
    "yearDiscovered": 1774,
    "oxidationStates": "7, 6, 5, 4, 3, 2, 1, -1, -2, -3",
    "electronegativity": 1.55,
    "ionisationEnergy": 717,
    "atomicRadius": 1.61,
    "covalentRadius": 1.39,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 12.91,
    "heatOfVaporisation": 221,
    "molarHeatCapacity": 26.32,
    "meltingPoint": 1519,
    "boilingPoint": 2334,
    "density": 7.21,
    "atomicMass": 54.938044,
    "crystalStructure": "body-centered cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7439-96-5",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Iron",
    "symbol": "Fe",
    "atomicNumber": 26,
    "block": "d-block",
    "group": 8,
    "period": 4,
    "category": "transition",
    "electronConfig": "[Ar] 3d6 4s2",
    "yearDiscovered": "Ancient",
    "oxidationStates": "-4, -2, -1, +1, +2, +3, +4, +5, +6",
    "electronegativity": 1.83,
    "ionisationEnergy": 763,
    "atomicRadius": 1.56,
    "covalentRadius": 1.25,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 13.81,
    "heatOfVaporisation": 340,
    "molarHeatCapacity": 25.1,
    "meltingPoint": 1811,
    "boilingPoint": 3134,
    "density": 7.874,
    "atomicMass": 55.845,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "ferromagnetic",
    "casNumber": "7439-89-6",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Cobalt",
    "symbol": "Co",
    "atomicNumber": 27,
    "block": "d-block",
    "group": 9,
    "period": 4,
    "category": "transition",
    "electronConfig": "[Ar] 3d7 4s2",
    "yearDiscovered": "Ancient",
    "oxidationStates": "-3, -1, +1, +2, +3, +4, +5",
    "electronegativity": 1.88,
    "ionisationEnergy": 760,
    "atomicRadius": 1.52,
    "covalentRadius": 1.26,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 16.06,
    "heatOfVaporisation": 377,
    "molarHeatCapacity": 24.81,
    "meltingPoint": 1768,
    "boilingPoint": 3200,
    "density": 8.9,
    "atomicMass": 58.933194,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "ferromagnetic",
    "casNumber": "7440-48-4",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Nickel",
    "symbol": "Ni",
    "atomicNumber": 28,
    "block": "d-block",
    "group": 10,
    "period": 4,
    "category": "transition",
    "electronConfig": "[Ar] 3d8 4s2",
    "yearDiscovered": 1751,
    "oxidationStates": "4, 3, 2, 1, -1, -2",
    "electronegativity": 1.91,
    "ionisationEnergy": 737,
    "atomicRadius": 1.49,
    "covalentRadius": 1.21,
    "vanDerWaalsRadius": 1.63,
    "phase": "solid",
    "heatOfFusion": 17.48,
    "heatOfVaporisation": 379,
    "molarHeatCapacity": 26.07,
    "meltingPoint": 1728,
    "boilingPoint": 3003,
    "density": 8.908,
    "atomicMass": 58.6934,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "ferromagnetic",
    "casNumber": "7440-02-0",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Copper",
    "symbol": "Cu",
    "atomicNumber": 29,
    "block": "d-block",
    "group": 11,
    "period": 4,
    "category": "transition",
    "electronConfig": "[Ar] 3d10 4s1",
    "yearDiscovered": "Ancient",
    "oxidationStates": "-2, +1, +2, +3, +4",
    "electronegativity": 1.9,
    "ionisationEnergy": 746,
    "atomicRadius": 1.45,
    "covalentRadius": 1.38,
    "vanDerWaalsRadius": 1.4,
    "phase": "solid",
    "heatOfFusion": 13.26,
    "heatOfVaporisation": 300.4,
    "molarHeatCapacity": 24.44,
    "meltingPoint": 1357.77,
    "boilingPoint": 2835,
    "density": 8.96,
    "atomicMass": 63.546,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-50-8",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Zinc",
    "symbol": "Zn",
    "atomicNumber": 30,
    "block": "d-block",
    "group": 12,
    "period": 4,
    "category": "transition",
    "electronConfig": "[Ar] 3d10 4s2",
    "yearDiscovered": 1746,
    "oxidationStates": "-2, 0, +1, +2",
    "electronegativity": 1.65,
    "ionisationEnergy": 906,
    "atomicRadius": 1.42,
    "covalentRadius": 1.31,
    "vanDerWaalsRadius": 1.39,
    "phase": "solid",
    "heatOfFusion": 7.32,
    "heatOfVaporisation": 115,
    "molarHeatCapacity": 25.47,
    "meltingPoint": 692.68,
    "boilingPoint": 1180,
    "density": 7.14,
    "atomicMass": 65.38,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-66-6",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Gallium",
    "symbol": "Ga",
    "atomicNumber": 31,
    "block": "p-block",
    "group": 13,
    "period": 4,
    "category": "post-transition",
    "electronConfig": "[Ar] 3d10 4s2 4p1",
    "yearDiscovered": 1875,
    "oxidationStates": "3, 2, 1, -1, -2, -4, -5",
    "electronegativity": 1.81,
    "ionisationEnergy": 579,
    "atomicRadius": 1.36,
    "covalentRadius": 1.26,
    "vanDerWaalsRadius": 1.87,
    "phase": "solid",
    "heatOfFusion": 5.59,
    "heatOfVaporisation": 256,
    "molarHeatCapacity": 25.86,
    "meltingPoint": 302.9146,
    "boilingPoint": 2673,
    "density": 5.91,
    "atomicMass": 69.723,
    "crystalStructure": "orthorhombic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-55-3",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Germanium",
    "symbol": "Ge",
    "atomicNumber": 32,
    "block": "p-block",
    "group": 14,
    "period": 4,
    "category": "metalloid",
    "electronConfig": "[Ar] 3d10 4s2 4p2",
    "yearDiscovered": 1886,
    "oxidationStates": "4, 3, 2, 1, 0, -1, -2, -3, -4",
    "electronegativity": 2.01,
    "ionisationEnergy": 762,
    "atomicRadius": 1.25,
    "covalentRadius": 1.22,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 36.94,
    "heatOfVaporisation": 334,
    "molarHeatCapacity": 23.222,
    "meltingPoint": 1211.4,
    "boilingPoint": 3106,
    "density": 5.323,
    "atomicMass": 72.63,
    "crystalStructure": "face-centered diamond-cubic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-56-4",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Arsenic",
    "symbol": "As",
    "atomicNumber": 33,
    "block": "p-block",
    "group": 15,
    "period": 4,
    "category": "metalloid",
    "electronConfig": "[Ar] 3d10 4s2 4p3",
    "yearDiscovered": "Ancient",
    "oxidationStates": "5, 4, 3, 2, 1, -1, -2, -3",
    "electronegativity": 2.18,
    "ionisationEnergy": 947,
    "atomicRadius": 1.14,
    "covalentRadius": 1.19,
    "vanDerWaalsRadius": 1.85,
    "phase": "solid",
    "heatOfFusion": 24.44,
    "heatOfVaporisation": 34.76,
    "molarHeatCapacity": 24.64,
    "meltingPoint": 1090.15,
    "boilingPoint": 886.15,
    "density": 5.727,
    "atomicMass": 74.921595,
    "crystalStructure": "rhombohedral",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-38-2",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Selenium",
    "symbol": "Se",
    "atomicNumber": 34,
    "block": "p-block",
    "group": 16,
    "period": 4,
    "category": "nonmetal",
    "electronConfig": "[Ar] 3d10 4s2 4p4",
    "yearDiscovered": 1817,
    "oxidationStates": "6, 5, 4, 3, 2, 1, -1, -2",
    "electronegativity": 2.55,
    "ionisationEnergy": 941,
    "atomicRadius": 1.03,
    "covalentRadius": 1.16,
    "vanDerWaalsRadius": 1.9,
    "phase": "solid",
    "heatOfFusion": 6.69,
    "heatOfVaporisation": 95.48,
    "molarHeatCapacity": 25.363,
    "meltingPoint": 494,
    "boilingPoint": 958,
    "density": 4.81,
    "atomicMass": 78.971,
    "crystalStructure": "hexagonal",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7782-49-2",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Bromine",
    "symbol": "Br",
    "atomicNumber": 35,
    "block": "p-block",
    "group": 17,
    "period": 4,
    "category": "halogen",
    "electronConfig": "[Ar] 3d10 4s2 4p5",
    "yearDiscovered": 1826,
    "oxidationStates": "7, 5, 4, 3, 1, -1",
    "electronegativity": 2.96,
    "ionisationEnergy": 1140,
    "atomicRadius": 0.94,
    "covalentRadius": 1.14,
    "vanDerWaalsRadius": 1.85,
    "phase": "liquid",
    "heatOfFusion": 10.571,
    "heatOfVaporisation": 29.96,
    "molarHeatCapacity": 75.69,
    "meltingPoint": 265.8,
    "boilingPoint": 332,
    "density": 3.1028,
    "atomicMass": 79.904,
    "crystalStructure": "orthorhombic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7726-95-6",
    "bondingType": "covalent",
    "": ""
  },
  {
    "name": "Krypton",
    "symbol": "Kr",
    "atomicNumber": 36,
    "block": "p-block",
    "group": 18,
    "period": 4,
    "category": "noble gas",
    "electronConfig": "[Ar] 3d10 4s2 4p6",
    "yearDiscovered": 1898,
    "oxidationStates": "2, 1, 0",
    "electronegativity": 3,
    "ionisationEnergy": 1351,
    "atomicRadius": 0.88,
    "covalentRadius": 1.1,
    "vanDerWaalsRadius": 2.02,
    "phase": "gas",
    "heatOfFusion": 1.64,
    "heatOfVaporisation": 9.08,
    "molarHeatCapacity": 20.95,
    "meltingPoint": 115.78,
    "boilingPoint": 119.93,
    "density": "n/a",
    "atomicMass": 83.798,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7439-90-9",
    "bondingType": "atomic",
    "": ""
  },
  {
    "name": "Rubidium",
    "symbol": "Rb",
    "atomicNumber": 37,
    "block": "s-block",
    "group": 1,
    "period": 5,
    "category": "alkali",
    "electronConfig": "[Kr] 5s1",
    "yearDiscovered": 1861,
    "oxidationStates": "+1, -1",
    "electronegativity": 0.82,
    "ionisationEnergy": 403,
    "atomicRadius": 2.65,
    "covalentRadius": 2.11,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 2.19,
    "heatOfVaporisation": 69,
    "molarHeatCapacity": 31.06,
    "meltingPoint": 312.45,
    "boilingPoint": 961,
    "density": 1.532,
    "atomicMass": 85.4678,
    "crystalStructure": "body-centered cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-17-7",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Strontium",
    "symbol": "Sr",
    "atomicNumber": 38,
    "block": "s-block",
    "group": 2,
    "period": 5,
    "category": "alkaline earth",
    "electronConfig": "[Kr] 5s2",
    "yearDiscovered": 1790,
    "oxidationStates": "2, 1",
    "electronegativity": 0.95,
    "ionisationEnergy": 550,
    "atomicRadius": 2.19,
    "covalentRadius": 1.92,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 7.43,
    "heatOfVaporisation": 141,
    "molarHeatCapacity": 26.4,
    "meltingPoint": 1050,
    "boilingPoint": 1650,
    "density": 2.64,
    "atomicMass": 87.62,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-24-6",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Yttrium",
    "symbol": "Y",
    "atomicNumber": 39,
    "block": "d-block",
    "group": 3,
    "period": 5,
    "category": "transition",
    "electronConfig": "[Kr] 4d1 5s2",
    "yearDiscovered": 1794,
    "oxidationStates": "3, 2, 1",
    "electronegativity": 1.22,
    "ionisationEnergy": 600,
    "atomicRadius": 2.12,
    "covalentRadius": 1.62,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 11.42,
    "heatOfVaporisation": 363,
    "molarHeatCapacity": 26.53,
    "meltingPoint": 1799,
    "boilingPoint": 3203,
    "density": 4.472,
    "atomicMass": 88.90584,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-65-5",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Zirconium",
    "symbol": "Zr",
    "atomicNumber": 40,
    "block": "d-block",
    "group": 4,
    "period": 5,
    "category": "transition",
    "electronConfig": "[Kr] 4d2 5s2",
    "yearDiscovered": 1789,
    "oxidationStates": "4, 3, 2, 1, -2",
    "electronegativity": 1.33,
    "ionisationEnergy": 640,
    "atomicRadius": 2.06,
    "covalentRadius": 1.48,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 14,
    "heatOfVaporisation": 591,
    "molarHeatCapacity": 25.36,
    "meltingPoint": 2128,
    "boilingPoint": 4650,
    "density": 6.52,
    "atomicMass": 91.224,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-67-7",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Niobium",
    "symbol": "Nb",
    "atomicNumber": 41,
    "block": "d-block",
    "group": 5,
    "period": 5,
    "category": "transition",
    "electronConfig": "[Kr] 4d4 5s1",
    "yearDiscovered": 1801,
    "oxidationStates": "5, 4, 3, 2, 1, -1, -3",
    "electronegativity": 1.6,
    "ionisationEnergy": 652,
    "atomicRadius": 1.98,
    "covalentRadius": 1.37,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 30,
    "heatOfVaporisation": 689.9,
    "molarHeatCapacity": 24.6,
    "meltingPoint": 2750,
    "boilingPoint": 5017,
    "density": 8.57,
    "atomicMass": 92.90637,
    "crystalStructure": "body-centered cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-03-01",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Molybdenum",
    "symbol": "Mo",
    "atomicNumber": 42,
    "block": "d-block",
    "group": 6,
    "period": 5,
    "category": "transition",
    "electronConfig": "[Kr] 4d5 5s1",
    "yearDiscovered": 1778,
    "oxidationStates": "6, 5, 4, 3, 2, 1, -1, -2, -4",
    "electronegativity": 2.16,
    "ionisationEnergy": 684,
    "atomicRadius": 1.9,
    "covalentRadius": 1.45,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 37.48,
    "heatOfVaporisation": 598,
    "molarHeatCapacity": 24.06,
    "meltingPoint": 2896,
    "boilingPoint": 4912,
    "density": 10.28,
    "atomicMass": 95.95,
    "crystalStructure": "body-centered cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7439-98-7",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Technetium",
    "symbol": "Tc",
    "atomicNumber": 43,
    "block": "d-block",
    "group": 7,
    "period": 5,
    "category": "transition",
    "electronConfig": "[Kr] 4d5 5s2",
    "yearDiscovered": 1937,
    "oxidationStates": "7, 6, 5, 4, 3, 2, 1, -1, -3",
    "electronegativity": 1.9,
    "ionisationEnergy": 702,
    "atomicRadius": 1.83,
    "covalentRadius": 1.56,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 33.29,
    "heatOfVaporisation": 585.2,
    "molarHeatCapacity": 24.27,
    "meltingPoint": 2430,
    "boilingPoint": 4538,
    "density": 11,
    "atomicMass": 98,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "Paramagnetic",
    "casNumber": "7440-26-8",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Ruthenium",
    "symbol": "Ru",
    "atomicNumber": 44,
    "block": "d-block",
    "group": 8,
    "period": 5,
    "category": "transition",
    "electronConfig": "[Kr] 4d7 5s1",
    "yearDiscovered": 1827,
    "oxidationStates": "-4, -2, 1, 2, 3, 4, 5, 6, 7, 8",
    "electronegativity": 2.2,
    "ionisationEnergy": 710,
    "atomicRadius": 1.78,
    "covalentRadius": 1.26,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 38.59,
    "heatOfVaporisation": 619,
    "molarHeatCapacity": 24.06,
    "meltingPoint": 2607,
    "boilingPoint": 4423,
    "density": 12.45,
    "atomicMass": 101.07,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-18-8",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Rhodium",
    "symbol": "Rh",
    "atomicNumber": 45,
    "block": "d-block",
    "group": 9,
    "period": 5,
    "category": "transition",
    "electronConfig": "[Kr] 4d8 5s1",
    "yearDiscovered": 1803,
    "oxidationStates": "6, 5, 4, 3, 2, 1, -1, -3",
    "electronegativity": 2.28,
    "ionisationEnergy": 720,
    "atomicRadius": 1.73,
    "covalentRadius": 1.35,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 26.59,
    "heatOfVaporisation": 493,
    "molarHeatCapacity": 24.98,
    "meltingPoint": 2237,
    "boilingPoint": 3968,
    "density": 12.41,
    "atomicMass": 102.9055,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-16-6",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Palladium",
    "symbol": "Pd",
    "atomicNumber": 46,
    "block": "d-block",
    "group": 10,
    "period": 5,
    "category": "transition",
    "electronConfig": "[Kr] 4d10",
    "yearDiscovered": 1803,
    "oxidationStates": "0, +1, +2, +3, +4, +5, +6",
    "electronegativity": 2.2,
    "ionisationEnergy": 804,
    "atomicRadius": 1.69,
    "covalentRadius": 1.31,
    "vanDerWaalsRadius": 1.63,
    "phase": "solid",
    "heatOfFusion": 16.74,
    "heatOfVaporisation": 358,
    "molarHeatCapacity": 25.98,
    "meltingPoint": 1828.05,
    "boilingPoint": 3236,
    "density": 12.023,
    "atomicMass": 106.42,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-05-03",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Silver",
    "symbol": "Ag",
    "atomicNumber": 47,
    "block": "d-block",
    "group": 11,
    "period": 5,
    "category": "transition",
    "electronConfig": "[Kr] 4d10 5s1",
    "yearDiscovered": "Ancient",
    "oxidationStates": "-2, -1, 1, 2, 3, 4",
    "electronegativity": 1.93,
    "ionisationEnergy": 731,
    "atomicRadius": 1.65,
    "covalentRadius": 1.53,
    "vanDerWaalsRadius": 1.72,
    "phase": "solid",
    "heatOfFusion": 11.28,
    "heatOfVaporisation": 254,
    "molarHeatCapacity": 25.35,
    "meltingPoint": 1234.93,
    "boilingPoint": 2435,
    "density": 10.49,
    "atomicMass": 107.8682,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-22-4",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Cadmium",
    "symbol": "Cd",
    "atomicNumber": 48,
    "block": "d-block",
    "group": 12,
    "period": 5,
    "category": "transition",
    "electronConfig": "[Kr] 4d10 5s2",
    "yearDiscovered": 1817,
    "oxidationStates": "2, 1, -2",
    "electronegativity": 1.69,
    "ionisationEnergy": 868,
    "atomicRadius": 1.61,
    "covalentRadius": 1.48,
    "vanDerWaalsRadius": 1.58,
    "phase": "solid",
    "heatOfFusion": 6.21,
    "heatOfVaporisation": 99.87,
    "molarHeatCapacity": 26.02,
    "meltingPoint": 594.22,
    "boilingPoint": 1040,
    "density": 8.65,
    "atomicMass": 112.414,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-43-9",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Indium",
    "symbol": "In",
    "atomicNumber": 49,
    "block": "p-block",
    "group": 13,
    "period": 5,
    "category": "post-transition",
    "electronConfig": "[Kr] 4d10 5s2 5p1",
    "yearDiscovered": 1863,
    "oxidationStates": "3, 2, 1, -1, -2, -5",
    "electronegativity": 1.78,
    "ionisationEnergy": 558,
    "atomicRadius": 1.56,
    "covalentRadius": 1.44,
    "vanDerWaalsRadius": 1.93,
    "phase": "solid",
    "heatOfFusion": 3.281,
    "heatOfVaporisation": 231.8,
    "molarHeatCapacity": 26.74,
    "meltingPoint": 429.7485,
    "boilingPoint": 2345,
    "density": 7.31,
    "atomicMass": 114.818,
    "crystalStructure": "tetragonal",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-74-6",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Tin",
    "symbol": "Sn",
    "atomicNumber": 50,
    "block": "p-block",
    "group": 14,
    "period": 5,
    "category": "post-transition",
    "electronConfig": "[Kr] 4d10 5s2 5p2",
    "yearDiscovered": "Ancient",
    "oxidationStates": "4, 3, 2, 1, -1, -2, -3, -4",
    "electronegativity": 1.96,
    "ionisationEnergy": 709,
    "atomicRadius": 1.45,
    "covalentRadius": 1.41,
    "vanDerWaalsRadius": 2.17,
    "phase": "solid",
    "heatOfFusion": 7.03,
    "heatOfVaporisation": 296.1,
    "molarHeatCapacity": 27.112,
    "meltingPoint": 505.08,
    "boilingPoint": 2875,
    "density": 7.265,
    "atomicMass": 118.71,
    "crystalStructure": "face-centered diamond-cubic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-31-5",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Antimony",
    "symbol": "Sb",
    "atomicNumber": 51,
    "block": "p-block",
    "group": 15,
    "period": 5,
    "category": "metalloid",
    "electronConfig": "[Kr] 4d10 5s2 5p3",
    "yearDiscovered": "Ancient",
    "oxidationStates": "5, 4, 3, 2, 1, -1, -2, -3",
    "electronegativity": 2.05,
    "ionisationEnergy": 834,
    "atomicRadius": 1.33,
    "covalentRadius": 1.38,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 19.79,
    "heatOfVaporisation": 193.43,
    "molarHeatCapacity": 25.23,
    "meltingPoint": 903.78,
    "boilingPoint": 1908,
    "density": 6.697,
    "atomicMass": 121.76,
    "crystalStructure": "rhombohedral",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-36-0",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Tellurium",
    "symbol": "Te",
    "atomicNumber": 52,
    "block": "p-block",
    "group": 16,
    "period": 5,
    "category": "metalloid",
    "electronConfig": "[Kr] 4d10 5s2 5p4",
    "yearDiscovered": 1782,
    "oxidationStates": "6, 5, 4, 3, 2, 1, -1, -2",
    "electronegativity": 2.1,
    "ionisationEnergy": 869,
    "atomicRadius": 1.23,
    "covalentRadius": 1.35,
    "vanDerWaalsRadius": 2.06,
    "phase": "solid",
    "heatOfFusion": 17.49,
    "heatOfVaporisation": 114.1,
    "molarHeatCapacity": 25.73,
    "meltingPoint": 722.66,
    "boilingPoint": 1261,
    "density": 6.24,
    "atomicMass": 127.6,
    "crystalStructure": "hexagonal",
    "magneticOrdering": "diamagnetic",
    "casNumber": "13494-80-9",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Iodine",
    "symbol": "I",
    "atomicNumber": 53,
    "block": "p-block",
    "group": 17,
    "period": 5,
    "category": "halogen",
    "electronConfig": "[Kr] 4d10 5s2 5p5",
    "yearDiscovered": 1811,
    "oxidationStates": "7, 6, 5, 4, 3, 1, -1",
    "electronegativity": 2.66,
    "ionisationEnergy": 1008,
    "atomicRadius": 1.15,
    "covalentRadius": 1.33,
    "vanDerWaalsRadius": 1.98,
    "phase": "solid",
    "heatOfFusion": 15.52,
    "heatOfVaporisation": 41.57,
    "molarHeatCapacity": 54.44,
    "meltingPoint": 386.85,
    "boilingPoint": 457.4,
    "density": 4.933,
    "atomicMass": 126.90447,
    "crystalStructure": "orthorhombic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7553-56-2",
    "bondingType": "covalent",
    "": ""
  },
  {
    "name": "Xenon",
    "symbol": "Xe",
    "atomicNumber": 54,
    "block": "p-block",
    "group": 18,
    "period": 5,
    "category": "noble gas",
    "electronConfig": "[Kr] 4d10 5s2 5p6",
    "yearDiscovered": 1898,
    "oxidationStates": "0, +1, +2, +4, +6, +8",
    "electronegativity": 2.6,
    "ionisationEnergy": 1170,
    "atomicRadius": 1.08,
    "covalentRadius": 1.3,
    "vanDerWaalsRadius": 2.16,
    "phase": "gas",
    "heatOfFusion": 2.27,
    "heatOfVaporisation": 12.64,
    "molarHeatCapacity": 21.01,
    "meltingPoint": 161.4,
    "boilingPoint": 165.051,
    "density": "n/a",
    "atomicMass": 131.293,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-63-3",
    "bondingType": "atomic",
    "": ""
  },
  {
    "name": "Cesium",
    "symbol": "Cs",
    "atomicNumber": 55,
    "block": "s-block",
    "group": 1,
    "period": 6,
    "category": "alkali",
    "electronConfig": "[Xe] 6s1",
    "yearDiscovered": 1860,
    "oxidationStates": "+1, -1",
    "electronegativity": 0.79,
    "ionisationEnergy": 376,
    "atomicRadius": 2.98,
    "covalentRadius": 2.25,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 2.09,
    "heatOfVaporisation": 63.9,
    "molarHeatCapacity": 32.21,
    "meltingPoint": 301.7,
    "boilingPoint": 944,
    "density": 1.93,
    "atomicMass": 132.905452,
    "crystalStructure": "body-centred cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-46-2",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Barium",
    "symbol": "Ba",
    "atomicNumber": 56,
    "block": "s-block",
    "group": 2,
    "period": 6,
    "category": "alkaline earth",
    "electronConfig": "[Xe] 6s2",
    "yearDiscovered": 1808,
    "oxidationStates": "+2, +1",
    "electronegativity": 0.89,
    "ionisationEnergy": 503,
    "atomicRadius": 2.53,
    "covalentRadius": 1.98,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 7.12,
    "heatOfVaporisation": 142,
    "molarHeatCapacity": 28.07,
    "meltingPoint": 1000,
    "boilingPoint": 2118,
    "density": 3.51,
    "atomicMass": 137.327,
    "crystalStructure": "body-centered cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-39-3",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Lanthanum",
    "symbol": "La",
    "atomicNumber": 57,
    "block": "f-block",
    "group": "n/a",
    "period": 6,
    "category": "lanthanoid",
    "electronConfig": "[Xe] 5d1 6s2",
    "yearDiscovered": 1839,
    "oxidationStates": "3, 2, 1",
    "electronegativity": 1.1,
    "ionisationEnergy": 538,
    "atomicRadius": 1.95,
    "covalentRadius": 1.69,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 6.2,
    "heatOfVaporisation": 400,
    "molarHeatCapacity": 27.11,
    "meltingPoint": 1193,
    "boilingPoint": 3737,
    "density": 6.162,
    "atomicMass": 138.90547,
    "crystalStructure": "double hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7439-91-0",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Cerium",
    "symbol": "Ce",
    "atomicNumber": 58,
    "block": "f-block",
    "group": "n/a",
    "period": 6,
    "category": "lanthanoid",
    "electronConfig": "[Xe] 4f1 5d1 6s2",
    "yearDiscovered": 1803,
    "oxidationStates": "4, 3, 2, 1",
    "electronegativity": 1.12,
    "ionisationEnergy": 534,
    "atomicRadius": 1.85,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 5.46,
    "heatOfVaporisation": 398,
    "molarHeatCapacity": 26.94,
    "meltingPoint": 1068,
    "boilingPoint": 3716,
    "density": 6.77,
    "atomicMass": 140.116,
    "crystalStructure": "face-centred cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-45-1",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Praseodymium",
    "symbol": "Pr",
    "atomicNumber": 59,
    "block": "f-block",
    "group": "n/a",
    "period": 6,
    "category": "lanthanoid",
    "electronConfig": "[Xe] 4f3 6s2",
    "yearDiscovered": 1885,
    "oxidationStates": "5, 4, 3, 2",
    "electronegativity": 1.13,
    "ionisationEnergy": 527,
    "atomicRadius": 2.47,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 6.89,
    "heatOfVaporisation": 331,
    "molarHeatCapacity": 27.2,
    "meltingPoint": 1208,
    "boilingPoint": 3403,
    "density": 6.77,
    "atomicMass": 140.90766,
    "crystalStructure": "double hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-10-0",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Neodymium",
    "symbol": "Nd",
    "atomicNumber": 60,
    "block": "f-block",
    "group": "n/a",
    "period": 6,
    "category": "lanthanoid",
    "electronConfig": "[Xe] 4f4 6s2",
    "yearDiscovered": 1885,
    "oxidationStates": "+4, +3, +2",
    "electronegativity": 1.14,
    "ionisationEnergy": 533,
    "atomicRadius": 2.06,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 7.14,
    "heatOfVaporisation": 289,
    "molarHeatCapacity": 27.45,
    "meltingPoint": 1297,
    "boilingPoint": 3347,
    "density": 7.01,
    "atomicMass": 144.242,
    "crystalStructure": "double hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-00-8",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Promethium",
    "symbol": "Pm",
    "atomicNumber": 61,
    "block": "f-block",
    "group": "n/a",
    "period": 6,
    "category": "lanthanoid",
    "electronConfig": "[Xe] 4f5 6s2",
    "yearDiscovered": 1947,
    "oxidationStates": "3, 2",
    "electronegativity": 1.13,
    "ionisationEnergy": 540,
    "atomicRadius": 2.05,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 7.13,
    "heatOfVaporisation": 289,
    "molarHeatCapacity": "n/a",
    "meltingPoint": 1315,
    "boilingPoint": 3273,
    "density": 7.26,
    "atomicMass": 145,
    "crystalStructure": "double hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-12-02",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Samarium",
    "symbol": "Sm",
    "atomicNumber": 62,
    "block": "f-block",
    "group": "n/a",
    "period": 6,
    "category": "lanthanoid",
    "electronConfig": "[Xe] 4f6 6s2",
    "yearDiscovered": 1853,
    "oxidationStates": "4, 3, 2, 1",
    "electronegativity": 1.17,
    "ionisationEnergy": 545,
    "atomicRadius": 2.38,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 8.62,
    "heatOfVaporisation": 192,
    "molarHeatCapacity": 29.54,
    "meltingPoint": 1345,
    "boilingPoint": 2173,
    "density": 7.52,
    "atomicMass": 150.36,
    "crystalStructure": "rhombohedral",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-19-9",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Europium",
    "symbol": "Eu",
    "atomicNumber": 63,
    "block": "f-block",
    "group": "n/a",
    "period": 6,
    "category": "lanthanoid",
    "electronConfig": "[Xe] 4f7 6s2",
    "yearDiscovered": 1901,
    "oxidationStates": "3, 2, 1",
    "electronegativity": 1.2,
    "ionisationEnergy": 547,
    "atomicRadius": 2.31,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 9.21,
    "heatOfVaporisation": 176,
    "molarHeatCapacity": 27.66,
    "meltingPoint": 1099,
    "boilingPoint": 1802,
    "density": 5.264,
    "atomicMass": 151.964,
    "crystalStructure": "body-centered cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-53-1",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Gadolinium",
    "symbol": "Gd",
    "atomicNumber": 64,
    "block": "f-block",
    "group": "n/a",
    "period": 6,
    "category": "lanthanoid",
    "electronConfig": "[Xe] 4f7 5d1 6s2",
    "yearDiscovered": 1880,
    "oxidationStates": "1, 2, 3",
    "electronegativity": 1.2,
    "ionisationEnergy": 593,
    "atomicRadius": 2.33,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 10.05,
    "heatOfVaporisation": 301.3,
    "molarHeatCapacity": 37.03,
    "meltingPoint": 1585,
    "boilingPoint": 3273,
    "density": 7.9,
    "atomicMass": 157.25,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "ferromagnetic",
    "casNumber": "7440-54-2",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Terbium",
    "symbol": "Tb",
    "atomicNumber": 65,
    "block": "f-block",
    "group": "n/a",
    "period": 6,
    "category": "lanthanoid",
    "electronConfig": "[Xe] 4f9 6s2",
    "yearDiscovered": 1843,
    "oxidationStates": "4, 3, 2, 1",
    "electronegativity": 1.2,
    "ionisationEnergy": 566,
    "atomicRadius": 2.25,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 10.15,
    "heatOfVaporisation": 391,
    "molarHeatCapacity": 28.91,
    "meltingPoint": 1629,
    "boilingPoint": 3396,
    "density": 8.23,
    "atomicMass": 158.92535,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-27-9",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Dysprosium",
    "symbol": "Dy",
    "atomicNumber": 66,
    "block": "f-block",
    "group": "n/a",
    "period": 6,
    "category": "lanthanoid",
    "electronConfig": "[Xe] 4f10 6s2",
    "yearDiscovered": 1886,
    "oxidationStates": "4, 3, 2, 1",
    "electronegativity": 1.22,
    "ionisationEnergy": 573,
    "atomicRadius": 2.28,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 11.06,
    "heatOfVaporisation": 280,
    "molarHeatCapacity": 27.7,
    "meltingPoint": 1680,
    "boilingPoint": 2840,
    "density": 8.54,
    "atomicMass": 162.5,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7429-91-6",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Holmium",
    "symbol": "Ho",
    "atomicNumber": 67,
    "block": "f-block",
    "group": "n/a",
    "period": 6,
    "category": "lanthanoid",
    "electronConfig": "[Xe] 4f11 6s2",
    "yearDiscovered": 1878,
    "oxidationStates": "3, 2, 1",
    "electronegativity": 1.23,
    "ionisationEnergy": 581,
    "atomicRadius": 2.26,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 17,
    "heatOfVaporisation": 251,
    "molarHeatCapacity": 27.15,
    "meltingPoint": 1734,
    "boilingPoint": 2873,
    "density": 8.79,
    "atomicMass": 164.93033,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-60-0",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Erbium",
    "symbol": "Er",
    "atomicNumber": 68,
    "block": "f-block",
    "group": "n/a",
    "period": 6,
    "category": "lanthanoid",
    "electronConfig": "[Xe] 4f12 6s2",
    "yearDiscovered": 1842,
    "oxidationStates": "3, 2, 1",
    "electronegativity": 1.24,
    "ionisationEnergy": 589,
    "atomicRadius": 2.26,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 19.9,
    "heatOfVaporisation": 280,
    "molarHeatCapacity": 28.12,
    "meltingPoint": 1802,
    "boilingPoint": 3141,
    "density": 9.066,
    "atomicMass": 167.259,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-52-0",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Thulium",
    "symbol": "Tm",
    "atomicNumber": 69,
    "block": "f-block",
    "group": "n/a",
    "period": 6,
    "category": "lanthanoid",
    "electronConfig": "[Xe] 4f13 6s2",
    "yearDiscovered": 1879,
    "oxidationStates": "2, 3",
    "electronegativity": 1.25,
    "ionisationEnergy": 597,
    "atomicRadius": 2.22,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 16.84,
    "heatOfVaporisation": 191,
    "molarHeatCapacity": 27.03,
    "meltingPoint": 1818,
    "boilingPoint": 2223,
    "density": 9.32,
    "atomicMass": 168.93422,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-30-4",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Ytterbium",
    "symbol": "Yb",
    "atomicNumber": 70,
    "block": "f-block",
    "group": "n/a",
    "period": 6,
    "category": "lanthanoid",
    "electronConfig": "[Xe] 4f14 6s2",
    "yearDiscovered": 1878,
    "oxidationStates": "3, 2, 1",
    "electronegativity": 1.1,
    "ionisationEnergy": 603,
    "atomicRadius": 2.22,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 7.66,
    "heatOfVaporisation": 129,
    "molarHeatCapacity": 26.74,
    "meltingPoint": 1097,
    "boilingPoint": 1469,
    "density": 6.9,
    "atomicMass": 173.045,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-64-4",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Lutetium",
    "symbol": "Lu",
    "atomicNumber": 71,
    "block": "d-block",
    "group": "n/a",
    "period": 6,
    "category": "lanthanoid",
    "electronConfig": "[Xe] 4f14 5d1 6s2",
    "yearDiscovered": 1907,
    "oxidationStates": "3, 2, 1",
    "electronegativity": 1.27,
    "ionisationEnergy": 524,
    "atomicRadius": 2.17,
    "covalentRadius": 1.6,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 22,
    "heatOfVaporisation": 414,
    "molarHeatCapacity": 26.86,
    "meltingPoint": 1925,
    "boilingPoint": 3675,
    "density": 9.841,
    "atomicMass": 174.9668,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7439-94-3",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Hafnium",
    "symbol": "Hf",
    "atomicNumber": 72,
    "block": "d-block",
    "group": 4,
    "period": 6,
    "category": "transition",
    "electronConfig": "[Xe] 4f14 5d2 6s2",
    "yearDiscovered": 1923,
    "oxidationStates": "4, 3, 2, 1, -2",
    "electronegativity": 1.3,
    "ionisationEnergy": 659,
    "atomicRadius": 2.08,
    "covalentRadius": 1.5,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 27.2,
    "heatOfVaporisation": 648,
    "molarHeatCapacity": 25.73,
    "meltingPoint": 2506,
    "boilingPoint": 4876,
    "density": 13.31,
    "atomicMass": 178.49,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-58-6",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Tantalum",
    "symbol": "Ta",
    "atomicNumber": 73,
    "block": "d-block",
    "group": 5,
    "period": 6,
    "category": "transition",
    "electronConfig": "[Xe] 4f14 5d3 6s2",
    "yearDiscovered": 1802,
    "oxidationStates": "5, 4, 3, 2, 1, -1, -3",
    "electronegativity": 1.5,
    "ionisationEnergy": 761,
    "atomicRadius": 2,
    "covalentRadius": 1.38,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 36.57,
    "heatOfVaporisation": 753,
    "molarHeatCapacity": 25.36,
    "meltingPoint": 3290,
    "boilingPoint": 5731,
    "density": 16.69,
    "atomicMass": 180.94788,
    "crystalStructure": "tetragonal",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-25-7",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Tungsten",
    "symbol": "W",
    "atomicNumber": 74,
    "block": "d-block",
    "group": 6,
    "period": 6,
    "category": "transition",
    "electronConfig": "[Xe] 4f14 5d4 6s2",
    "yearDiscovered": 1783,
    "oxidationStates": "6, 5, 4, 3, 2, 1, 0, -1, -2, -4",
    "electronegativity": 2.36,
    "ionisationEnergy": 770,
    "atomicRadius": 1.93,
    "covalentRadius": 1.46,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 35.3,
    "heatOfVaporisation": 774,
    "molarHeatCapacity": 24.27,
    "meltingPoint": 3695,
    "boilingPoint": 6203,
    "density": 19.25,
    "atomicMass": 183.84,
    "crystalStructure": "body-centered cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-33-7",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Rhenium",
    "symbol": "Re",
    "atomicNumber": 75,
    "block": "d-block",
    "group": 7,
    "period": 6,
    "category": "transition",
    "electronConfig": "[Xe] 4f14 5d5 6s2",
    "yearDiscovered": 1925,
    "oxidationStates": "7, 6, 5, 4, 3, 2, 1, 0, -1, -3",
    "electronegativity": 1.9,
    "ionisationEnergy": 760,
    "atomicRadius": 1.88,
    "covalentRadius": 1.59,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 60.43,
    "heatOfVaporisation": 704,
    "molarHeatCapacity": 25.48,
    "meltingPoint": 3459,
    "boilingPoint": 5903,
    "density": 21.02,
    "atomicMass": 186.207,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-15-5",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Osmium",
    "symbol": "Os",
    "atomicNumber": 76,
    "block": "d-block",
    "group": 8,
    "period": 6,
    "category": "transition",
    "electronConfig": "[Xe] 4f14 5d6 6s2",
    "yearDiscovered": 1803,
    "oxidationStates": "8, 7, 6, 5, 4, 3, 2, 1, 0, -1, -2, -4",
    "electronegativity": 2.2,
    "ionisationEnergy": 840,
    "atomicRadius": 1.85,
    "covalentRadius": 1.28,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 31,
    "heatOfVaporisation": 378,
    "molarHeatCapacity": 24.7,
    "meltingPoint": 3306,
    "boilingPoint": 5285,
    "density": 22.59,
    "atomicMass": 190.23,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-04-02",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Iridium",
    "symbol": "Ir",
    "atomicNumber": 77,
    "block": "d-block",
    "group": 9,
    "period": 6,
    "category": "transition",
    "electronConfig": "[Xe] 4f14 5d7 6s2",
    "yearDiscovered": 1803,
    "oxidationStates": "-3, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9",
    "electronegativity": 2.2,
    "ionisationEnergy": 880,
    "atomicRadius": 1.8,
    "covalentRadius": 1.37,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 41.12,
    "heatOfVaporisation": 564,
    "molarHeatCapacity": 25.1,
    "meltingPoint": 2719,
    "boilingPoint": 4403,
    "density": 22.56,
    "atomicMass": 192.217,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7439-88-5",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Platinum",
    "symbol": "Pt",
    "atomicNumber": 78,
    "block": "d-block",
    "group": 10,
    "period": 6,
    "category": "transition",
    "electronConfig": "[Xe] 4f14 5d9 6s1",
    "yearDiscovered": "Ancient",
    "oxidationStates": "6, 5, 4, 3, 2, 1, -1, -2, -3",
    "electronegativity": 2.28,
    "ionisationEnergy": 870,
    "atomicRadius": 1.77,
    "covalentRadius": 1.28,
    "vanDerWaalsRadius": 1.75,
    "phase": "solid",
    "heatOfFusion": 22.17,
    "heatOfVaporisation": 510,
    "molarHeatCapacity": 25.86,
    "meltingPoint": 2041.4,
    "boilingPoint": 4098,
    "density": 21.45,
    "atomicMass": 195.084,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-06-04",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Gold",
    "symbol": "Au",
    "atomicNumber": 79,
    "block": "d-block",
    "group": 11,
    "period": 6,
    "category": "transition",
    "electronConfig": "[Xe] 4f14 5d10 6s1",
    "yearDiscovered": "Ancient",
    "oxidationStates": "5, 3, 2, 1, -1, -2, -3",
    "electronegativity": 2.54,
    "ionisationEnergy": 890,
    "atomicRadius": 1.74,
    "covalentRadius": 1.44,
    "vanDerWaalsRadius": 1.66,
    "phase": "solid",
    "heatOfFusion": 12.55,
    "heatOfVaporisation": 342,
    "molarHeatCapacity": 25.418,
    "meltingPoint": 1337.33,
    "boilingPoint": 3243,
    "density": 19.3,
    "atomicMass": 196.966569,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-57-5",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Mercury",
    "symbol": "Hg",
    "atomicNumber": 80,
    "block": "d-block",
    "group": 12,
    "period": 6,
    "category": "transition",
    "electronConfig": "[Xe] 4f14 5d10 6s2",
    "yearDiscovered": "Ancient",
    "oxidationStates": "2 , 1 , -2",
    "electronegativity": 2,
    "ionisationEnergy": 1007,
    "atomicRadius": 1.71,
    "covalentRadius": 1.49,
    "vanDerWaalsRadius": 1.55,
    "phase": "liquid",
    "heatOfFusion": 2.29,
    "heatOfVaporisation": 59.11,
    "molarHeatCapacity": 27.983,
    "meltingPoint": 234.321,
    "boilingPoint": 629.88,
    "density": 13.534,
    "atomicMass": 200.592,
    "crystalStructure": "rhombohedral",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7439-97-6",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Thallium",
    "symbol": "Tl",
    "atomicNumber": 81,
    "block": "p-block",
    "group": 13,
    "period": 6,
    "category": "post-transition",
    "electronConfig": "[Xe] 4f14 5d10 6s2 6p1",
    "yearDiscovered": 1861,
    "oxidationStates": "3, 2, 1, -1, -2, -5",
    "electronegativity": 2.04,
    "ionisationEnergy": 589,
    "atomicRadius": 1.56,
    "covalentRadius": 1.48,
    "vanDerWaalsRadius": 1.96,
    "phase": "solid",
    "heatOfFusion": 4.14,
    "heatOfVaporisation": 165,
    "molarHeatCapacity": 26.32,
    "meltingPoint": 577,
    "boilingPoint": 1746,
    "density": 11.85,
    "atomicMass": 204.38,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-28-0",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Lead",
    "symbol": "Pb",
    "atomicNumber": 82,
    "block": "p-block",
    "group": 14,
    "period": 6,
    "category": "post-transition",
    "electronConfig": "[Xe] 4f14 5d10 6s2 6p2",
    "yearDiscovered": "Ancient",
    "oxidationStates": "4, 3, 2, 1, -1, -2, -4",
    "electronegativity": 2.33,
    "ionisationEnergy": 716,
    "atomicRadius": 1.54,
    "covalentRadius": 1.47,
    "vanDerWaalsRadius": 2.02,
    "phase": "solid",
    "heatOfFusion": 4.77,
    "heatOfVaporisation": 179.5,
    "molarHeatCapacity": 26.65,
    "meltingPoint": 600.61,
    "boilingPoint": 2022,
    "density": 11.34,
    "atomicMass": 207.2,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7439-92-1",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Bismuth",
    "symbol": "Bi",
    "atomicNumber": 83,
    "block": "p-block",
    "group": 15,
    "period": 6,
    "category": "post-transition",
    "electronConfig": "[Xe] 4f14 5d10 6s2 6p3",
    "yearDiscovered": "Ancient",
    "oxidationStates": "5, 4, 3, 2, 1, -1, -2, -3",
    "electronegativity": 2.02,
    "ionisationEnergy": 703,
    "atomicRadius": 1.43,
    "covalentRadius": 1.46,
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 11.3,
    "heatOfVaporisation": 179,
    "molarHeatCapacity": 25.52,
    "meltingPoint": 544.7,
    "boilingPoint": 1837,
    "density": 9.78,
    "atomicMass": 208.9804,
    "crystalStructure": "rhombohedral",
    "magneticOrdering": "diamagnetic",
    "casNumber": "7440-69-9",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Polonium",
    "symbol": "Po",
    "atomicNumber": 84,
    "block": "p-block",
    "group": 16,
    "period": 6,
    "category": "metalloid",
    "electronConfig": "[Xe] 4f14 5d10 6s2 6p4",
    "yearDiscovered": 1898,
    "oxidationStates": "6, 5, 4, 2, -2",
    "electronegativity": 2,
    "ionisationEnergy": 812,
    "atomicRadius": 1.35,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 13,
    "heatOfVaporisation": 102.91,
    "molarHeatCapacity": 26.4,
    "meltingPoint": 527,
    "boilingPoint": 1235,
    "density": 9.196,
    "atomicMass": 209,
    "crystalStructure": "rhombohedral",
    "magneticOrdering": "nonmagnetic",
    "casNumber": "7440-08-06",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Astatine",
    "symbol": "At",
    "atomicNumber": 85,
    "block": "p-block",
    "group": 17,
    "period": 6,
    "category": "halogen",
    "electronConfig": "[Xe] 4f14 5d10 6s2 6p5",
    "yearDiscovered": 1940,
    "oxidationStates": "-1, +1, +3, +5, +7",
    "electronegativity": 2.2,
    "ionisationEnergy": 920,
    "atomicRadius": 1.27,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": "n/a",
    "heatOfVaporisation": 54.39,
    "molarHeatCapacity": "n/a",
    "meltingPoint": 575,
    "boilingPoint": 610,
    "density": 6.35,
    "atomicMass": 210,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "n/a",
    "casNumber": "7440-68-8",
    "bondingType": "covalent",
    "": ""
  },
  {
    "name": "Radon",
    "symbol": "Rn",
    "atomicNumber": 86,
    "block": "p-block",
    "group": 18,
    "period": 6,
    "category": "noble gas",
    "electronConfig": "[Xe] 4f14 5d10 6s2 6p6",
    "yearDiscovered": 1900,
    "oxidationStates": "6, 2, 0",
    "electronegativity": 2.2,
    "ionisationEnergy": 1037,
    "atomicRadius": 1.2,
    "covalentRadius": 1.45,
    "vanDerWaalsRadius": "n/a",
    "phase": "gas",
    "heatOfFusion": 3.247,
    "heatOfVaporisation": 18.1,
    "molarHeatCapacity": 20.786,
    "meltingPoint": 202,
    "boilingPoint": 211.5,
    "density": "n/a",
    "atomicMass": 222,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "non-magnetic",
    "casNumber": "10043-92-2",
    "bondingType": "atomic",
    "": ""
  },
  {
    "name": "Francium",
    "symbol": "Fr",
    "atomicNumber": 87,
    "block": "s-block",
    "group": 1,
    "period": 7,
    "category": "alkali",
    "electronConfig": "[Rn] 7s1",
    "yearDiscovered": 1939,
    "oxidationStates": 1,
    "electronegativity": 0.7,
    "ionisationEnergy": 380,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 2,
    "heatOfVaporisation": 65,
    "molarHeatCapacity": "n/a",
    "meltingPoint": -300,
    "boilingPoint": -950,
    "density": 2.9,
    "atomicMass": 223,
    "crystalStructure": "body-centered cubic",
    "magneticOrdering": "Paramagnetic",
    "casNumber": "7440-73-5",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Radium",
    "symbol": "Ra",
    "atomicNumber": 88,
    "block": "s-block",
    "group": 2,
    "period": 7,
    "category": "alkaline earth",
    "electronConfig": "[Rn] 7s2",
    "yearDiscovered": 1898,
    "oxidationStates": 2,
    "electronegativity": 0.9,
    "ionisationEnergy": 509,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 8.5,
    "heatOfVaporisation": 113,
    "molarHeatCapacity": "n/a",
    "meltingPoint": 973,
    "boilingPoint": 2010,
    "density": 5.5,
    "atomicMass": 226,
    "crystalStructure": "body-centered cubic",
    "magneticOrdering": "nonmagnetic",
    "casNumber": "7440-14-4",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Actinium",
    "symbol": "Ac",
    "atomicNumber": 89,
    "block": "f-block",
    "group": "n/a",
    "period": 7,
    "category": "actinoid",
    "electronConfig": "[Rn] 6d1 7s2",
    "yearDiscovered": 1899,
    "oxidationStates": "3, 2",
    "electronegativity": 1.1,
    "ionisationEnergy": 499,
    "atomicRadius": 1.95,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 14,
    "heatOfVaporisation": 400,
    "molarHeatCapacity": 27.2,
    "meltingPoint": 1500,
    "boilingPoint": 3500,
    "density": 10,
    "atomicMass": 227,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "n/a",
    "casNumber": "7440-34-8",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Thorium",
    "symbol": "Th",
    "atomicNumber": 90,
    "block": "f-block",
    "group": "n/a",
    "period": 7,
    "category": "actinoid",
    "electronConfig": "[Rn] 6d2 7s2",
    "yearDiscovered": 1828,
    "oxidationStates": "4, 3, 2, 1",
    "electronegativity": 1.3,
    "ionisationEnergy": 587,
    "atomicRadius": 1.8,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 13.81,
    "heatOfVaporisation": 514,
    "molarHeatCapacity": 26.23,
    "meltingPoint": 2023,
    "boilingPoint": 5061,
    "density": 11.7,
    "atomicMass": 232.0377,
    "crystalStructure": "face-centred cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-29-1",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Protactinium",
    "symbol": "Pa",
    "atomicNumber": 91,
    "block": "f-block",
    "group": "n/a",
    "period": 7,
    "category": "actinoid",
    "electronConfig": "[Rn] 5f2 6d1 7s2",
    "yearDiscovered": 1913,
    "oxidationStates": "2, 3, 4, 5",
    "electronegativity": 1.5,
    "ionisationEnergy": 568,
    "atomicRadius": 1.8,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 12.34,
    "heatOfVaporisation": 481,
    "molarHeatCapacity": "n/a",
    "meltingPoint": 1841,
    "boilingPoint": 4300,
    "density": 15.37,
    "atomicMass": 231.03588,
    "crystalStructure": "tetragonal",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-13-3",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Uranium",
    "symbol": "U",
    "atomicNumber": 92,
    "block": "f-block",
    "group": "n/a",
    "period": 7,
    "category": "actinoid",
    "electronConfig": "[Rn] 5f3 6d1 7s2",
    "yearDiscovered": 1789,
    "oxidationStates": "6, 5, 4, 3, 2, 1",
    "electronegativity": 1.38,
    "ionisationEnergy": 598,
    "atomicRadius": 1.75,
    "covalentRadius": 1.86,
    "vanDerWaalsRadius": 1.86,
    "phase": "solid",
    "heatOfFusion": 9.14,
    "heatOfVaporisation": 417.1,
    "molarHeatCapacity": 27.665,
    "meltingPoint": 1405.3,
    "boilingPoint": 4404,
    "density": 19.1,
    "atomicMass": 238.02891,
    "crystalStructure": "orthorhombic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-61-1",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Neptunium",
    "symbol": "Np",
    "atomicNumber": 93,
    "block": "f-block",
    "group": "n/a",
    "period": 7,
    "category": "actinoid",
    "electronConfig": "[Rn] 5f4 6d1 7s2",
    "yearDiscovered": 1940,
    "oxidationStates": "7, 6, 5, 4, 3, 2",
    "electronegativity": 1.36,
    "ionisationEnergy": 605,
    "atomicRadius": 1.75,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 5.19,
    "heatOfVaporisation": 336,
    "molarHeatCapacity": 29.46,
    "meltingPoint": 912,
    "boilingPoint": 4447,
    "density": 20.45,
    "atomicMass": 237,
    "crystalStructure": "orthorhombic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7439-99-8",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Plutonium",
    "symbol": "Pu",
    "atomicNumber": 94,
    "block": "f-block",
    "group": "n/a",
    "period": 7,
    "category": "actinoid",
    "electronConfig": "[Rn] 5f6 7s2",
    "yearDiscovered": 1940,
    "oxidationStates": "8, 7, 6, 5, 4, 3, 2, 1",
    "electronegativity": 1.28,
    "ionisationEnergy": 585,
    "atomicRadius": 1.75,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 2.82,
    "heatOfVaporisation": 333.5,
    "molarHeatCapacity": 35.5,
    "meltingPoint": 912.5,
    "boilingPoint": 3505,
    "density": 19.816,
    "atomicMass": 244,
    "crystalStructure": "monoclinic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-07-05",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Americium",
    "symbol": "Am",
    "atomicNumber": 95,
    "block": "f-block",
    "group": "n/a",
    "period": 7,
    "category": "actinoid",
    "electronConfig": "[Rn] 5f7 7s2",
    "yearDiscovered": 1944,
    "oxidationStates": "8, 7, 6, 5, 4, 3, 2",
    "electronegativity": 1.3,
    "ionisationEnergy": 578,
    "atomicRadius": 1.75,
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 14.39,
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": 62.7,
    "meltingPoint": 1449,
    "boilingPoint": 2880,
    "density": 12,
    "atomicMass": 243,
    "crystalStructure": "double hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-35-9",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Curium",
    "symbol": "Cm",
    "atomicNumber": 96,
    "block": "f-block",
    "group": "n/a",
    "period": 7,
    "category": "actinoid",
    "electronConfig": "[Rn] 5f7 6d1 7s2",
    "yearDiscovered": 1944,
    "oxidationStates": "6, 4, 3, 2",
    "electronegativity": 1.3,
    "ionisationEnergy": 581,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 13.85,
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": "n/a",
    "meltingPoint": 1613,
    "boilingPoint": 3383,
    "density": 13.51,
    "atomicMass": 247,
    "crystalStructure": "double hexagonal close-packed",
    "magneticOrdering": "antiferromagnetic",
    "casNumber": "7440-51-9",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Berkelium",
    "symbol": "Bk",
    "atomicNumber": 97,
    "block": "f-block",
    "group": "n/a",
    "period": 7,
    "category": "actinoid",
    "electronConfig": "[Rn] 5f9 7s2",
    "yearDiscovered": 1949,
    "oxidationStates": "2, 3, 4",
    "electronegativity": 1.3,
    "ionisationEnergy": 601,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 7.92,
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": "n/a",
    "meltingPoint": 1259,
    "boilingPoint": 2900,
    "density": 14.78,
    "atomicMass": 247,
    "crystalStructure": "double hexagonal close-packed",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7440-40-6",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Californium",
    "symbol": "Cf",
    "atomicNumber": 98,
    "block": "f-block",
    "group": "n/a",
    "period": 7,
    "category": "actinoid",
    "electronConfig": "[Rn] 5f10 7s2",
    "yearDiscovered": 1950,
    "oxidationStates": "2, 3, 4",
    "electronegativity": 1.3,
    "ionisationEnergy": 608,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": "n/a",
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": "n/a",
    "meltingPoint": 1173,
    "boilingPoint": 1743,
    "density": 15.1,
    "atomicMass": 251,
    "crystalStructure": "double hexagonal close-packed",
    "magneticOrdering": "n/a",
    "casNumber": "7440-71-3",
    "bondingType": "metallic",
    "": ""
  },
  {
    "name": "Einsteinium",
    "symbol": "Es",
    "atomicNumber": 99,
    "block": "f-block",
    "group": "n/a",
    "period": 7,
    "category": "actinoid",
    "electronConfig": "[Rn] 5f11 7s2",
    "yearDiscovered": 1952,
    "oxidationStates": "2, 3, 4",
    "electronegativity": 1.3,
    "ionisationEnergy": 619,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": "n/a",
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": "n/a",
    "meltingPoint": 1133,
    "boilingPoint": 1269,
    "density": 8.84,
    "atomicMass": 252,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "paramagnetic",
    "casNumber": "7429-92-7",
    "bondingType": "n/a",
    "": ""
  },
  {
    "name": "Fermium",
    "symbol": "Fm",
    "atomicNumber": 100,
    "block": "f-block",
    "group": "n/a",
    "period": 7,
    "category": "actinoid",
    "electronConfig": "[Rn] 5f12 7s2",
    "yearDiscovered": 1952,
    "oxidationStates": "2, 3",
    "electronegativity": 1.3,
    "ionisationEnergy": 627,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": "n/a",
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": "n/a",
    "meltingPoint": 1800,
    "boilingPoint": "n/a",
    "density": 9.71,
    "atomicMass": 257,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "n/a",
    "casNumber": "7440-72-4",
    "bondingType": "n/a",
    "": ""
  },
  {
    "name": "Mendelevium",
    "symbol": "Md",
    "atomicNumber": 101,
    "block": "f-block",
    "group": "n/a",
    "period": 7,
    "category": "actinoid",
    "electronConfig": "[Rn] 5f13 7s2",
    "yearDiscovered": 1955,
    "oxidationStates": "2, 3",
    "electronegativity": 1.3,
    "ionisationEnergy": 635,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": "n/a",
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": "n/a",
    "meltingPoint": 1100,
    "boilingPoint": "n/a",
    "density": 10.37,
    "atomicMass": 258,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "n/a",
    "casNumber": "7440-11-01",
    "bondingType": "n/a",
    "": ""
  },
  {
    "name": "Nobelium",
    "symbol": "No",
    "atomicNumber": 102,
    "block": "f-block",
    "group": "n/a",
    "period": 7,
    "category": "actinoid",
    "electronConfig": "[Rn] 5f14 7s2",
    "yearDiscovered": 1957,
    "oxidationStates": "2, 3",
    "electronegativity": 1.3,
    "ionisationEnergy": 642,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": "n/a",
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": "n/a",
    "meltingPoint": 1100,
    "boilingPoint": "n/a",
    "density": 9.94,
    "atomicMass": 259,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "n/a",
    "casNumber": "10028-14-5",
    "bondingType": "n/a",
    "": ""
  },
  {
    "name": "Lawrencium",
    "symbol": "Lr",
    "atomicNumber": 103,
    "block": "d-block",
    "group": "n/a",
    "period": 7,
    "category": "actinoid",
    "electronConfig": "[Rn] 5f14 7s2 7p1",
    "yearDiscovered": 1961,
    "oxidationStates": 3,
    "electronegativity": 1.3,
    "ionisationEnergy": 478,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": "n/a",
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": "n/a",
    "meltingPoint": 1900,
    "boilingPoint": "n/a",
    "density": 16,
    "atomicMass": 266,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "n/a",
    "casNumber": "22537-19-5",
    "bondingType": "n/a",
    "": ""
  },
  {
    "name": "Rutherfordium",
    "symbol": "Rf",
    "atomicNumber": 104,
    "block": "d-block",
    "group": 4,
    "period": 7,
    "category": "transition",
    "electronConfig": "[Rn] 5f14 6d2 7s2",
    "yearDiscovered": 1969,
    "oxidationStates": 4,
    "electronegativity": "n/a",
    "ionisationEnergy": 580,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": "n/a",
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": "n/a",
    "meltingPoint": "n/a",
    "boilingPoint": "n/a",
    "density": 23.2,
    "atomicMass": 267,
    "crystalStructure": "n/a",
    "magneticOrdering": "n/a",
    "casNumber": "53850-36-5",
    "bondingType": "n/a",
    "": ""
  },
  {
    "name": "Dubnium",
    "symbol": "Db",
    "atomicNumber": 105,
    "block": "d-block",
    "group": 5,
    "period": 7,
    "category": "transition",
    "electronConfig": "[Rn] 5f14 6d3 7s2",
    "yearDiscovered": 1967,
    "oxidationStates": 5,
    "electronegativity": "n/a",
    "ionisationEnergy": 656,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": "n/a",
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": "n/a",
    "meltingPoint": "n/a",
    "boilingPoint": "n/a",
    "density": 29.3,
    "atomicMass": 268,
    "crystalStructure": "body-centered cubic",
    "magneticOrdering": "n/a",
    "casNumber": "53850-35-4",
    "bondingType": "n/a",
    "": ""
  },
  {
    "name": "Seaborgium",
    "symbol": "Sg",
    "atomicNumber": 106,
    "block": "d-block",
    "group": 6,
    "period": 7,
    "category": "transition",
    "electronConfig": "[Rn] 5f14 6d4 7s2",
    "yearDiscovered": 1974,
    "oxidationStates": "0, 6",
    "electronegativity": "n/a",
    "ionisationEnergy": 752,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": "n/a",
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": "n/a",
    "meltingPoint": "n/a",
    "boilingPoint": "n/a",
    "density": 35,
    "atomicMass": 269,
    "crystalStructure": "body-centered cubic",
    "magneticOrdering": "n/a",
    "casNumber": "54038-81-2",
    "bondingType": "n/a",
    "": ""
  },
  {
    "name": "Bohrium",
    "symbol": "Bh",
    "atomicNumber": 107,
    "block": "d-block",
    "group": 7,
    "period": 7,
    "category": "transition",
    "electronConfig": "[Rn] 5f14 6d5 7s2",
    "yearDiscovered": 1976,
    "oxidationStates": 7,
    "electronegativity": "n/a",
    "ionisationEnergy": 742,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": "n/a",
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": "n/a",
    "meltingPoint": "n/a",
    "boilingPoint": "n/a",
    "density": 37.1,
    "atomicMass": 270,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "n/a",
    "casNumber": "54037-14-8",
    "bondingType": "n/a",
    "": ""
  },
  {
    "name": "Hassium",
    "symbol": "Hs",
    "atomicNumber": 108,
    "block": "d-block",
    "group": 8,
    "period": 7,
    "category": "transition",
    "electronConfig": "[Rn] 5f14 6d6 7s2",
    "yearDiscovered": 1984,
    "oxidationStates": 8,
    "electronegativity": "n/a",
    "ionisationEnergy": 733,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": "n/a",
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": "n/a",
    "meltingPoint": "n/a",
    "boilingPoint": "n/a",
    "density": 41,
    "atomicMass": 269,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "n/a",
    "casNumber": "54037-57-9",
    "bondingType": "n/a",
    "": ""
  },
  {
    "name": "Meitnerium",
    "symbol": "Mt",
    "atomicNumber": 109,
    "block": "d-block",
    "group": 9,
    "period": 7,
    "category": "transition",
    "electronConfig": "[Rn] 5f14 6d7 7s2",
    "yearDiscovered": 1982,
    "oxidationStates": "9, 8, 6, 4, 3, 1",
    "electronegativity": "n/a",
    "ionisationEnergy": 800,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": "n/a",
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": "n/a",
    "meltingPoint": "n/a",
    "boilingPoint": "n/a",
    "density": 37.4,
    "atomicMass": 278,
    "crystalStructure": "face-centered cubic",
    "magneticOrdering": "paramagnetic (predicted)",
    "casNumber": "54038-01-6",
    "bondingType": "n/a",
    "": ""
  },
  {
    "name": "Darmstadtium",
    "symbol": "Ds",
    "atomicNumber": 110,
    "block": "d-block",
    "group": 10,
    "period": 7,
    "category": "transition",
    "electronConfig": "[Rn] 5f14 6d9 7s1",
    "yearDiscovered": 1994,
    "oxidationStates": "8, 6, 4, 2, 0",
    "electronegativity": "n/a",
    "ionisationEnergy": 955,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": "n/a",
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": "n/a",
    "meltingPoint": "n/a",
    "boilingPoint": "n/a",
    "density": 34.8,
    "atomicMass": 281,
    "crystalStructure": "body-centered cubic",
    "magneticOrdering": "n/a",
    "casNumber": "54083-77-1",
    "bondingType": "n/a",
    "": ""
  },
  {
    "name": "Roentgenium",
    "symbol": "Rg",
    "atomicNumber": 111,
    "block": "d-block",
    "group": 11,
    "period": 7,
    "category": "transition",
    "electronConfig": "[Rn] 5f14 6d10 7s1",
    "yearDiscovered": 1994,
    "oxidationStates": "5, 3, 1, -1",
    "electronegativity": "n/a",
    "ionisationEnergy": 1022,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": "n/a",
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": "n/a",
    "meltingPoint": "n/a",
    "boilingPoint": "n/a",
    "density": 28.7,
    "atomicMass": 282,
    "crystalStructure": "body-centered cubic",
    "magneticOrdering": "n/a",
    "casNumber": "54386-24-2",
    "bondingType": "n/a",
    "": ""
  },
  {
    "name": "Copernicium",
    "symbol": "Cn",
    "atomicNumber": 112,
    "block": "d-block",
    "group": 12,
    "period": 7,
    "category": "transition",
    "electronConfig": "[Rn] 5f14 6d10 7s2",
    "yearDiscovered": 1996,
    "oxidationStates": "4, 2, 1, 0",
    "electronegativity": "n/a",
    "ionisationEnergy": 1154,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "gas",
    "heatOfFusion": "n/a",
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": "n/a",
    "meltingPoint": "n/a",
    "boilingPoint": 357,
    "density": 23.7,
    "atomicMass": 285,
    "crystalStructure": "hexagonal close-packed",
    "magneticOrdering": "n/a",
    "casNumber": "54084-26-3",
    "bondingType": "n/a",
    "": ""
  },
  {
    "name": "Nihonium",
    "symbol": "Nh",
    "atomicNumber": 113,
    "block": "p-block",
    "group": 13,
    "period": 7,
    "category": "post-transition",
    "electronConfig": "[Rn] 5f14 6d10 7s2 7p1",
    "yearDiscovered": 2003,
    "oxidationStates": "-1, 1, 3, 5",
    "electronegativity": "n/a",
    "ionisationEnergy": 704,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 7.61,
    "heatOfVaporisation": 130,
    "molarHeatCapacity": "n/a",
    "meltingPoint": 700,
    "boilingPoint": 1400,
    "density": 16,
    "atomicMass": 286,
    "crystalStructure": "n/a",
    "magneticOrdering": "n/a",
    "casNumber": "54084-70-7",
    "bondingType": "n/a",
    "": ""
  },
  {
    "name": "Flerovium",
    "symbol": "Fl",
    "atomicNumber": 114,
    "block": "p-block",
    "group": 14,
    "period": 7,
    "category": "post-transition",
    "electronConfig": "[Rn] 5f14 6d10 7s2 7p2",
    "yearDiscovered": 1998,
    "oxidationStates": "0, 1, 2, 4, 6",
    "electronegativity": "n/a",
    "ionisationEnergy": 823,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": "n/a",
    "heatOfVaporisation": 38,
    "molarHeatCapacity": "n/a",
    "meltingPoint": 340,
    "boilingPoint": 420,
    "density": 14,
    "atomicMass": 289,
    "crystalStructure": "n/a",
    "magneticOrdering": "n/a",
    "casNumber": "54085-16-4",
    "bondingType": "n/a",
    "": ""
  },
  {
    "name": "Moscovium",
    "symbol": "Mc",
    "atomicNumber": 115,
    "block": "p-block",
    "group": 15,
    "period": 7,
    "category": "post-transition",
    "electronConfig": "[Rn] 5f14 6d10 7s2 7p3",
    "yearDiscovered": 2003,
    "oxidationStates": "1, 3",
    "electronegativity": "n/a",
    "ionisationEnergy": 823,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 5.94,
    "heatOfVaporisation": 138,
    "molarHeatCapacity": "n/a",
    "meltingPoint": 700,
    "boilingPoint": 1400,
    "density": 13.5,
    "atomicMass": 289,
    "crystalStructure": "n/a",
    "magneticOrdering": "n/a",
    "casNumber": "54085-64-2",
    "bondingType": "n/a",
    "": ""
  },
  {
    "name": "Livermorium",
    "symbol": "Lv",
    "atomicNumber": 116,
    "block": "p-block",
    "group": 16,
    "period": 7,
    "category": "post-transition",
    "electronConfig": "[Rn] 5f14 6d10 7s2 7p4",
    "yearDiscovered": 2000,
    "oxidationStates": "-2, +2, +4",
    "electronegativity": "n/a",
    "ionisationEnergy": 823,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 7.61,
    "heatOfVaporisation": 42,
    "molarHeatCapacity": "n/a",
    "meltingPoint": 709,
    "boilingPoint": 1085,
    "density": 12.9,
    "atomicMass": 293,
    "crystalStructure": "n/a",
    "magneticOrdering": "n/a",
    "casNumber": "54100-71-9",
    "bondingType": "n/a",
    "": ""
  },
  {
    "name": "Tennessine",
    "symbol": "Ts",
    "atomicNumber": 117,
    "block": "p-block",
    "group": 17,
    "period": 7,
    "category": "post-transition",
    "electronConfig": "[Rn] 5f14 6d10 7s2 7p5",
    "yearDiscovered": 2010,
    "oxidationStates": "-1, +1, +3, +5",
    "electronegativity": "n/a",
    "ionisationEnergy": 823,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": "n/a",
    "heatOfVaporisation": "n/a",
    "molarHeatCapacity": "n/a",
    "meltingPoint": 723,
    "boilingPoint": 883,
    "density": 7.2,
    "atomicMass": 294,
    "crystalStructure": "n/a",
    "magneticOrdering": "n/a",
    "casNumber": "54101-14-3",
    "bondingType": "n/a",
    "": ""
  },
  {
    "name": "Oganesson",
    "symbol": "Og",
    "atomicNumber": 118,
    "block": "p-block",
    "group": 18,
    "period": 7,
    "category": "noble gas",
    "electronConfig": "[Rn] 5f14 6d10 7s2 7p6",
    "yearDiscovered": 2002,
    "oxidationStates": "-1, 0, +1, +2, +4, +6",
    "electronegativity": "n/a",
    "ionisationEnergy": 823,
    "atomicRadius": "n/a",
    "covalentRadius": "n/a",
    "vanDerWaalsRadius": "n/a",
    "phase": "solid",
    "heatOfFusion": 23.5,
    "heatOfVaporisation": 19.4,
    "molarHeatCapacity": "n/a",
    "meltingPoint": "n/a",
    "boilingPoint": 350,
    "density": "n/a",
    "atomicMass": 294,
    "crystalStructure": "n/a",
    "magneticOrdering": "n/a",
    "casNumber": "54144-19-3",
    "bondingType": "n/a",
    "": ""
  }
]